<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="1">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="343" startPos="208" endPos="208" selMode="0" lang="Normal Text" encoding="-1" userReadOnly="no" filename="D:\Program Files\World of Warcraft\_classic_\Interface\AddOns\ConROC_Warrior\ConROC_Warrior.toc" backupFilePath="" originalFileLastModifTimestamp="-1915465951" originalFileLastModifTimestampHigh="30762631" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="7864439" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1134" startPos="19" endPos="19" selMode="0" lang="Normal Text" encoding="-1" userReadOnly="no" filename="D:\Program Files\World of Warcraft\_classic_\Interface\AddOns\ConROC_Warrior\changes.txt" backupFilePath="" originalFileLastModifTimestamp="906701277" originalFileLastModifTimestampHigh="30763070" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="771751936" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="126" xOffset="0" scrollWidth="301" startPos="4068" endPos="4068" selMode="0" lang="Lua" encoding="-1" userReadOnly="no" filename="D:\Program Files\World of Warcraft\_classic_\Interface\AddOns\ConROC_Warrior\warrior_ids.lua" backupFilePath="" originalFileLastModifTimestamp="944335332" originalFileLastModifTimestampHigh="30761785" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="2450" startPos="279" endPos="279" selMode="0" lang="Lua" encoding="-1" userReadOnly="no" filename="D:\Program Files\World of Warcraft\_classic_\Interface\AddOns\ConROC_Warrior\warrior.lua" backupFilePath="" originalFileLastModifTimestamp="-969457797" originalFileLastModifTimestampHigh="30763069" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="637" startPos="88" endPos="88" selMode="0" lang="Lua" encoding="-1" userReadOnly="no" filename="D:\Program Files\World of Warcraft\_classic_\Interface\AddOns\ConROC_Warrior\warrior_spellmenu.lua" backupFilePath="" originalFileLastModifTimestamp="-1118650276" originalFileLastModifTimestampHigh="30763069" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
        </subView>
    </Session>
</NotepadPlus>
