combined_plugin = {
	["name"] = "Combined DMG and HEAL",
	["icon"] = 236205,
	["source"] = false,
	["attribute"] = false,
	["spellid"] = false,
	["target"] = false,
	["author"] = "Razor170",
	["desc"] = "Creates custom display for DMG and HEAL Combined, Requested by Barlow",
	["script_version"] = 6,
	["script"] = "local Combat, CustomContainer, Instance = ...\n local total, top, amount = 0, 0, 0\n \n local damage_container = Combat:GetActorList ( DETAILS_ATTRIBUTE_DAMAGE )\n local healing_container = Combat:GetActorList ( DETAILS_ATTRIBUTE_HEAL )\n \n for i, actor in ipairs ( damage_container ) do\n 	if (actor:IsGroupPlayer()) then\n 		local damageDone = actor.total\n 		CustomContainer:AddValue ( actor, damageDone )\n 	end\n end\n \n for i, actor in ipairs ( healing_container ) do\n 	if (actor:IsGroupPlayer()) then\n 		if (CustomContainer:HasActor(actor)) then\n 			local healingDone = actor.total\n 			CustomContainer:AddValue ( actor, healingDone )\n 		else\n 			local healingDone = actor.total\n 			CustomContainer:AddValue ( actor, healingDone )\n 		end\n 	end\n end\n \n total, top = CustomContainer:GetTotalAndHighestValue()\n amount = CustomContainer:GetNumActors()\n return total, top, amount\n",
	["total_script"] = "				local value, top, total, combat, instance = ...\n				--get the time of current combat if the player is in combat\n		local CurrCombatTime = combat:GetCombatTime()\n				\n				--build the string\n				local ToK = Details:GetCurrentToKFunction()\n				local s = ToK (_, value / CurrCombatTime)\n				\n				if (instance.row_info.textR_show_data[3]) then\n				s = ToK (_, value) .. \" (\" .. s .. \", \"\n				else\n				s = ToK (_, value) .. \" (\" .. s\n				end\n				\n				return s\n				",
	["percent_script"] = false,
	["tooltip"] = "--get the parameters passed\nlocal actor, combat, instance = ... 				\n--get the cooltip object (we dont use the convencional GameTooltip here)\nlocal GameCooltip = GameCooltip2\n\n--Cooltip code\nlocal AllDmgSpells = {}\nlocal AllHealSpells = {}\n\n--dmg\nlocal player = combat [1]:GetActor (actor.nome)\nlocal playerSpells = player:GetSpellList()\nlocal damageDone = player.total\nlocal damagePS = damageDone / combat:GetCombatTime()\nfor spellID, spellTable in pairs (playerSpells) do\nAllDmgSpells [spellID] = spellTable.total\nend\n\n--heal\nlocal player = combat [2]:GetActor (actor.nome)\nlocal playerSpells = player:GetSpellList()\nlocal healingDone = player.total\nlocal healingPS = healingDone / combat:GetCombatTime()\nfor spellID, spellTable in pairs (playerSpells) do\nAllHealSpells [spellID] = spellTable.total\nend\n\n--sort table\nlocal sortedDmgList = {}\nlocal sortedHealList = {}\nfor spellID, total in pairs (AllDmgSpells) do\ntinsert (sortedDmgList, {spellID, total})\nend\ntable.sort (sortedDmgList, Details.Sort2)\nfor spellID, total in pairs (AllHealSpells) do\ntinsert (sortedHealList, {spellID, total})\nend\ntable.sort (sortedHealList, Details.Sort2)\n\n--get percentage\nlocal damagePercent = floor (100 * (damageDone / (damageDone + healingDone)))\nlocal healingPercent = floor (100 * (healingDone / (damageDone + healingDone)))\n\nlocal format_func = Details:GetCurrentToKFunction()\n\n--build the tooltip\nGameCooltip:AddLine (\"==== DAMAGE ====\")\nGameCooltip:AddLine (\"DPS:\", format_func(nil, damagePS))\nGameCooltip:AddLine (\"DMG Percent:\", format_func(nil, damagePercent) .. \"%\")\nfor i, t in ipairs (sortedDmgList) do\nlocal spellID, total = unpack (t)\nif (total > 1) then\nlocal spellName, _, spellIcon = Details.GetSpellInfo (spellID)\n\nGameCooltip:AddLine (spellName, format_func (_, total))\nDetails:AddTooltipBackgroundStatusbar()\nGameCooltip:AddIcon (spellIcon, 1, 1, _detalhes.tooltip.line_height, _detalhes.tooltip.line_height)\nend\nend\nGameCooltip:AddLine (\"==== HEALING ====\")\nGameCooltip:AddLine (\"HPS:\", format_func(nil, healingPS))\nGameCooltip:AddLine (\"HEAL Percent:\", format_func(nil, healingPercent) .. \"%\")\nfor i, t in ipairs (sortedHealList) do\nlocal spellID, total = unpack (t)\nif (total > 1) then\nlocal spellName, _, spellIcon = Details.GetSpellInfo (spellID)\n\nGameCooltip:AddLine (spellName, format_func (_, total))\nDetails:AddTooltipBackgroundStatusbar()\nGameCooltip:AddIcon (spellIcon, 1, 1, _detalhes.tooltip.line_height, _detalhes.tooltip.line_height)\nend\nend\n",
}

Details:InstallCustomObject (combined_plugin)