-- this file is autogenerated by WowUp (app) at Sat May 28 2022 02:15:44 GMT-0600 (Mountain Daylight Time)
WOWUP_DATA = {}
WOWUP_DATA.icon = "Interface/AddOns/wowup_data_addon/ldbicon"
WOWUP_DATA.addonManagerName = "WowUp"
WOWUP_DATA.addonManagerColorRGB = {232/255,205/255,134/255}
WOWUP_DATA.addonManagerNameSlashCommand = "/wowup"
WOWUP_DATA.updateAddonsList = {
  ["Raider.IO Mythic Plus, Raiding, and Recruitment"] = {"9.2.0 (v202205270600)", "9.2.0 (v202205280600)"},
}
