local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if ZGV:DoMutex("EventsC") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\Radiant Echoes")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\Azerothian Archives!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\The Big Dig: Traitor's Rest")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\Emerald Dreamsurge (Thaldraszus)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\Emerald Dreamsurge (The Waking Shores)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\Emerald Dreamsurge (Ohn'ahran Plains)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\Emerald Dreamsurge (The Azure Span)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Secrets of Azeroth\\Secrets of Azeroth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Secrets of Azeroth\\Community Rumors")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Secrets of Azeroth\\Secrets of Azeroth Mimiron's Jumpjets Mount")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\The Emerald Dream Superbloom")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\20th Anniversary Celebration\\20th Anniversary Event Weeklies")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\20th Anniversary Celebration\\Guest Relations")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\20th Anniversary Celebration\\Achievements\\A Cool Twenty Years")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\20th Anniversary Celebration\\Achievements\\I Have That One!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\20th Anniversary Celebration\\Achievements\\Fashion Critic")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\20th Anniversary Celebration\\Achievements\\Pet Mischief")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\20th Anniversary Celebration\\Achievements\\Balloonist")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\20th Anniversary Celebration\\Achievements\\Peanut Gallery")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\20th Anniversary Celebration\\Achievements\\An Original")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\20th Anniversary Celebration\\Achievements\\A Gatecrasher")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\20th Anniversary Celebration\\Achievements\\Codex Editor: Ahn'Qiraj")
ZGV.BETASTART()
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Pathfinder")
ZGV.BETAEND()
